server:
    port: 8082
    mode: "dev"
mysql:
    username: root
    password: 1
    host: 127.0.0.1
    port: 3306
    dbName: shopDevGo
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifeTime: 3600
logger:
    log_level: debug
    file_log_name: './logs/dev.log'
    max_size: 5
    max_backups: 3
    max_age: 28
    compress: true
redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0

